version: '3.8'

services:
  go-clean-arch-rest:
    container_name: go-app-rest
    restart: always
    volumes:
      - .:/app
    build:
      context: .
      dockerfile: cmd/http/DockerfileDev
    ports:
      - '5001:5001'
    networks:
      - bubble

  go-clean-arch-grpc:
    container_name: go-app-grpc
    restart: always
    volumes:
      - .:/app
    build:
      context: .
      dockerfile: cmd/grpc/DockerfileDev
    ports:
      - '5002:5002'
    networks:
      - bubble

  go-clean-arch-graphql:
    container_name: go-app-graphql
    restart: always
    volumes:
      - .:/app
    build:
      context: .
      dockerfile: cmd/graphql/DockerfileDev
    ports:
      - '5003:5003'
    networks:
      - bubble

  mysql:
    container_name: mysql
    image: mysql:8.0.32
    volumes:
      - clean-arch-mysql:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=clean-architecture
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - bubble

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - bubble

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    depends_on:
      - mongo
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
    networks:
      - bubble

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - '2181:2181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - bubble

  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    networks:
      - bubble

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui
    ports:
      - 8099:8080
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    networks:
      - bubble

  redis:
    container_name: redis
    image: redis
    ports:
      - '6379:6379'
    networks:
      - bubble

volumes:
  clean-arch-mysql:
  mongodb_data:
  kafka:

networks:
  bubble:
